spring.application.name=myAwesomeApp

# database
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${DB_PSWD}

#tworzy tabele na start
spring.jpa.hibernate.ddl-auto=create

#Basic Auth
spring.security.user.name=admin
spring.security.user.password=admin